import { getRandomTemplate } from "./template-registry";
import type {
  PageConfig,
  Stack,
  Pagetemplate,
  Section,
  SectionType,
  ProjectConfig,
  TemplateDefinition,
} from "@minions/shared";

import { getStackSpec } from "@minions/shared";
import { gettemplateSpec } from "./template-spec";

export function hashString(s: string) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function pick<T>(arr: T[], n: number) {
  return arr[Math.abs(n) % arr.length];
}

function makeAccent(
  template: string,
  seed: number,
  brief: string,
  stack: string
) {
  const palette = [
    "#4f46e5", // Indigo
    "#06b6d4", // Cyan
    "#22c55e", // Green
    "#f97316", // Orange
    "#ec4899", // Pink
    "#a855f7", // Purple
    "#eab308", // Yellow
    "#ef4444", // Red
    "#14b8a6", // Teal
    "#3b82f6", // Blue
    "#8b5cf6", // Violet
    "#d946ef", // Fuchsia
    "#f43f5e", // Rose
    "#84cc16", // Lime
    "#0ea5e9", // Sky
  ];
  const h = hashString(`${template}|${stack}|${seed}|${brief}`);
  return pick(palette, h);
}

function titleFromBrief(brief: string, fallback: string) {
  const t = (brief || "").trim();
  if (!t) return fallback;
  return t.split("\n")[0].slice(0, 48);
}

export function buildMockProject(opts: {
  template: string;
  brief: string;
  stack: Stack;
  seed: number;
  wordpressBaseUrl?: string;
  wordpressRestBase?: string;
}): ProjectConfig {
  const { template, brief, stack, seed } = opts;

  // 1. Pick Template
  const selectedTemplate = getRandomTemplate(template, seed);
  const themeMode = seed % 2 === 0 ? "dark" : "light"; // Simple alternating for now, or use hash

  // 2. Build Pages
  const pages: Record<string, PageConfig> = {};

  for (const pageDef of selectedTemplate.pages) {
    // Generate page config for each page in template
    // We modify the brief slightly to focus on the page context
    const pageBrief = `${brief}. ${pageDef.promptFocus}`;

    // Shift seed for each page so they are unique but deterministic
    // Using string hash of pageId to offset seed
    const pageSeed = seed + hashString(pageDef.id);

    pages[pageDef.id] = buildMockPageConfig({
      ...opts,
      template: template, // Keep project template (string), structure is from definition
      brief: pageBrief,
      seed: pageSeed,
      structure: pageDef.structure, // Explicit structure from template
      themeMode, // Pass consistent theme
    });
  }

  // 3. Assemble Project
  return {
    template: selectedTemplate.template, // Use the template string from definition (should match input)
    templateId: selectedTemplate.id,
    site: {
      siteName: titleFromBrief(brief, "Generated Site"),
      tagline: "Generated by MINIONS",
      primaryColor: makeAccent(template, seed, brief, stack),
      themeMode,
    },
    backend: {
      cms: "wordpress",
      wordpress: opts.wordpressBaseUrl
        ? { baseUrl: opts.wordpressBaseUrl, restBase: opts.wordpressRestBase }
        : { baseUrl: "", restBase: opts.wordpressRestBase },
    },
    pages,
    meta: {
      mode: "mock",
      generatedAt: new Date().toISOString(),
      seed,
      stack,
    },
  };
}

export function buildMockPageConfig(opts: {
  template: string;
  brief: string;
  stack: Stack;
  seed: number;
  wordpressBaseUrl?: string;
  wordpressRestBase?: string;
  structure?: SectionType[]; // Optional override
  themeMode?: "light" | "dark";
}): PageConfig {
  const { template, brief, stack, seed } = opts;

  // 1. Prepare deterministic hash
  const h = hashString(`${template}|${stack}|${seed}|${brief}`);

  // 2. Resolve Specs
  const stackSpec = getStackSpec(stack);
  const templateSpec = gettemplateSpec(template);

  // Resolve theme if not provided
  const themeMode = opts.themeMode || (seed % 2 === 0 ? "dark" : "light");

  // Helper: Deterministic shuffle
  function shuffle<T>(array: T[], seed: number): T[] {
    const copy = [...array];
    let m = copy.length,
      t,
      i;
    // LCG parameters
    let s = seed % 2147483647;
    if (s <= 0) s += 2147483646;

    const next = () => {
      s = (s * 16807) % 2147483647;
      return (s - 1) / 2147483646;
    };

    while (m) {
      i = Math.floor(next() * m--);
      t = copy[m];
      copy[m] = copy[i];
      copy[i] = t;
    }
    return copy;
  }

  // 3. Determine Sections Order
  let baseSections: SectionType[] = [];

  if (opts.structure) {
    // Explicit structure provided
    baseSections = [...opts.structure];
  } else {
    // Fallback to templateSpec logic (Single page legacy mode)
    const defaultOrder = templateSpec.defaultSectionOrder as SectionType[];

    const hasHero = defaultOrder[0] === "hero";
    const hasCta = defaultOrder[defaultOrder.length - 1] === "cta";

    let middle = defaultOrder.slice(
      hasHero ? 1 : 0,
      hasCta ? defaultOrder.length - 1 : defaultOrder.length
    );

    middle = shuffle(middle, h);

    baseSections = [
      ...(hasHero ? ["hero"] : []),
      ...middle,
      ...(hasCta ? ["cta"] : []),
    ] as SectionType[];
  }

  const wpBaseUrl = (opts.wordpressBaseUrl || "").trim() || "";
  const wpRestBase = (opts.wordpressRestBase || "").trim() || "/wp-json/wp/v2";

  const siteName = titleFromBrief(brief, "Generated Preview");
  const accent = makeAccent(template, seed, brief, stack);

  const sections = baseSections.map((t, idx) => {
    const secHash = h + idx * 13;
    const ctx = {
      h: secHash,
      stackSpec,
      stack,
      seed,
      siteName,
      wpBaseUrl,
      wpRestBase,
    };

    switch (t) {
      case "hero":
        return mockHero(ctx);
      case "features":
        return mockFeatures(ctx);
      case "testimonials":
        return mockTestimonials(ctx);
      case "faq":
        return mockFaq(ctx);
      case "blogList":
        return mockBlogList(ctx);
      case "pricing":
        return mockPricing(ctx);
      case "stats":
        return mockStats(ctx);
      case "team":
        return mockTeam(ctx);
      case "cta":
        return mockCta(ctx);
      case "productList":
        return mockProductList(ctx);
      case "productDetail":
        return mockProductDetail(ctx);
      default:
        return mockCta(ctx); // Fallback
    }
  }) as Section[];

  const page: PageConfig = {
    template,
    site: {
      siteName,
      tagline: "Generated by MINIONS",
      primaryColor: accent,
    },
    backend: {
      cms: "wordpress",
      wordpress: wpBaseUrl
        ? { baseUrl: wpBaseUrl, restBase: wpRestBase }
        : { baseUrl: "", restBase: wpRestBase },
    },
    sections,
    meta: {
      mode: "mock",
      generatedAt: new Date().toISOString(),
      seed,
      stack,
      note: "Mock generator via Stack Spec.",
    },
  };

  return page;
}

// --- Section Factories ---

type MockCtx = {
  h: number;
  stackSpec: any;
  stack: string;
  seed: number;
  siteName: string;
  wpBaseUrl: string;
  wpRestBase: string;
};

function mockHero(ctx: MockCtx) {
  const allowedVars = ctx.stackSpec.constraints.hero?.allowedVariants || [
    "center",
  ];
  const variant = pick(allowedVars, ctx.h);

  return {
    id: "hero-main",
    type: "hero",
    variant,
    eyebrow: `${ctx.stackSpec.label} Concept`.toUpperCase(),
    headline:
      variant === "split"
        ? `Your Idea: ${ctx.siteName}`
        : `Build ${ctx.siteName} with ${ctx.stackSpec.label}`,
    subheadline:
      "This is a mock generated based on your brief, seed, and selected stack constraints.",
    primaryCta: { label: "Generate (Live)", href: "#get-started" },
    secondaryCta: { label: "Learn More", href: "#examples" },
  };
}

function mockFeatures(ctx: MockCtx) {
  return {
    id: "features-main",
    type: "features",
    title: pick(
      ["Key Features", "Why Us?", "Highlights", "Core Benefits"],
      ctx.h
    ),
    subtitle: `Optimized for ${ctx.stackSpec.label} architecture.`,
    items: [
      {
        title: "Stack Optimized",
        description: `Generated specifically for ${ctx.stack} conventions.`,
      },
      {
        title: "Deterministic Mock",
        description: `Same seed (${ctx.seed}) = Same result.`,
      },
      {
        title: "Customizable",
        description: "Edit brief to change the tone/content keywords.",
      },
    ],
  };
}

function mockTestimonials(ctx: MockCtx) {
  return {
    id: "testimonials-main",
    type: "testimonials",
    title: "Testimonials",
    items: [
      {
        quote: `The ${ctx.stack} output structure is exactly what I needed.`,
        name: "Alex",
        role: "Developer",
      },
      {
        quote: "Mock generation is super fast and consistent.",
        name: "Sarah",
        role: "Product Manager",
      },
    ],
  };
}

function mockFaq(ctx: MockCtx) {
  return {
    id: "faq-main",
    type: "faq",
    title: "Frequently Asked Questions",
    items: [
      {
        q: "How does the stack selection affect output?",
        a: "It changes section ordering, constraints, and constraints valid for that framework.",
      },
      {
        q: "Can I export this?",
        a: "Yes, you can export the JSON config using the Export panel.",
      },
    ],
  };
}

function mockBlogList(ctx: MockCtx) {
  return {
    id: "blog-latest",
    type: "blogList",
    title: ctx.wpBaseUrl ? "From the Blog" : "Blog (Configure WP)",
    subtitle:
      ctx.wpBaseUrl ||
      ctx.stackSpec.constraints.blogList?.forceSourcetemplate === "wordpress"
        ? "Fetching from WordPress API"
        : "Connect your CMS to see real posts",
    maxItems: 3,
    source: {
      template: "wordpress",
      endpoint: "/posts?per_page=3&_embed",
    },
  };
}

function mockPricing(ctx: MockCtx) {
  return {
    id: "pricing-main",
    type: "pricing",
    title: "Simple, Transparent Pricing",
    subtitle: "Choose the plan that's right for you.",
    plans: [
      {
        name: "Starter",
        price: "$0",
        period: "/mo",
        description: "Perfect for hobbyists.",
        features: ["1 Project", "Community Support", "Basic Analytics"],
        cta: { label: "Start Free", href: "#free" },
      },
      {
        name: "Pro",
        price: "$29",
        period: "/mo",
        isPopular: true,
        description: "For serious developers.",
        features: [
          "Unlimited Projects",
          "Priority Support",
          "Advanced Analytics",
          "Custom Domain",
        ],
        cta: { label: "Get Pro", href: "#pro" },
      },
      {
        name: "Enterprise",
        price: "$99",
        period: "/mo",
        description: "For large teams.",
        features: [
          "SSO Integration",
          "Dedicated Success Manager",
          "SLA",
          "Audit Logs",
        ],
        cta: { label: "Contact Sales", href: "#contact" },
      },
    ],
  };
}

function mockStats(ctx: MockCtx) {
  return {
    id: "stats-main",
    type: "stats",
    title: "Trusted by Developers",
    variant: "card",
    items: [
      { value: "10k+", label: "Active Users", description: "Growing daily" },
      {
        value: "99.9%",
        label: "Uptime",
        description: "Enterprise grade reliability",
      },
      { value: "24/7", label: "Support", description: "We are always here" },
      { value: "500+", label: "Components", description: "Ready to use" },
    ],
  };
}

function mockTeam(ctx: MockCtx) {
  return {
    id: "team-main",
    type: "team",
    title: "Meet the Team",
    subtitle: "The experts behind the magic.",
    members: [
      {
        name: "Sarah Chen",
        role: "CEO & Founder",
        bio: "Visionary leader with 10+ years in Tech.",
        avatar: "/images/team-1.png",
      },
      {
        name: "David Miller",
        role: "CTO",
        bio: "Full stack wizard and open source contributor.",
        avatar: "/images/team-2.png",
      },
      {
        name: "Emily Davis",
        role: "Head of Design",
        bio: "Creating beautiful pixels and user experiences.",
        avatar: "/images/team-3.png",
      },
      {
        name: "Michael Wilson",
        role: "Lead Engineer",
        bio: "Architecting scalable systems.",
        avatar: "/images/team-4.png",
      },
    ],
  };
}

function mockCta(ctx: MockCtx) {
  return {
    id: "cta-bottom",
    type: "cta",
    title: "Ready to launch?",
    headline: "Start building today",
    subheadline: `Get your ${ctx.stackSpec.label} starter kit now.`,
    primaryCta: { label: "Get Started", href: "#get-started" },
  };
}

function mockProductList(ctx: MockCtx) {
  return {
    id: "products-grid",
    type: "productList",
    title: "Featured Collection",
    subtitle: "Handpicked items just for you.",
    maxItems: 6,
    displayMode: "grid",
  };
}

function mockProductDetail(ctx: MockCtx) {
  return {
    id: "product-main",
    type: "productDetail",
    showRelated: true,
    showReviews: true,
    // Add dummy product data for visual preview if CMS not connected
    mockProduct: {
      name: "Premium Mock Object",
      price: "$129.00",
      description:
        "This is a placeholder product generated by the mock system.",
      sku: "MOCK-001",
      images: [
        `https://picsum.photos/seed/${ctx.seed}/600/600`,
        `https://picsum.photos/seed/${ctx.seed + 1}/600/600`,
      ],
    },
  };
}
