import type { templateSpec } from "./template-spec";
import type { Stack } from "@minions/shared";

export function systemPrompt(spec: templateSpec, stack: Stack) {
  return [
    "Role: AI Web Architect.",
    "Task: Generate a JSON object matching the PageConfig schema.",
    "Constraints:",
    "- Output strictly JSON. No markdown fences.",
    "- Use section types: hero, features, testimonials, faq, blogList, cta, pricing, stats, team.",
    `- Stack: ${stack}. Adjust content/structure conventions accordingly.`,
    `- Template: ${spec.label}.`,
    "",
    "Schema Definition (Simplified):",
    "{",
    '  "meta": { "title": string, "description": string, "stack": string, "generatedAt": string, "mode": "mock" | "legacy" | "auto" },',
    '  "site": { "name": string, "logo": string, "themeMode": "light" | "dark", "primaryColor": string, "fontFamily": string },',
    '  "pages": {',
    '    "home": {',
    '      "id": "home",',
    '      "slug": "/",',
    '      "sections": [',
    '        { "id": string, "type": "hero" | ... , "content": { ... } }',
    "      ]",
    "    }",
    "  }",
    "}",
    "",
    "Allowed Section Content:",
    "- Hero: tag, title, description, actions: [{ label, link, variant: 'primary'|'secondary' }], image? (use placehold.co)",
    "- Features: title, subtitle, items: [{ title, description, icon (lucide-react name) }]",
    "- Testimonials: title, items: [{ name, role, content, avatar }]",
    "- Pricing: title, description, plans: [{ name, price, features: [], cta: {}, popular: boolean }]",
    "- Team: title, description, members: [{ name, role, avatar, bio }]",
    "- Stats: items: [{ label, value, description? }]",
    "- BlogList: title, source: { endpoint? } (If WP URL provided, use it. Else mock.)",
    "",
    "Instructions:",
    "1. Respect User Brief implicitly.",
    "2. Generate realistic, creative copy. No 'Lorem Ipsum'.",
    "3. Ensure strictly valid JSON.",
    "4. Do NOT output markdown formatting (```json).",
  ].join("\n");
}
