import { serverSupabaseUser, serverSupabaseClient } from "#supabase/server";
import type { Database } from "~/types/database.types";
import { GoogleGenerativeAI } from "@google/generative-ai";

export default defineEventHandler(async (event) => {
  const user = await serverSupabaseUser(event);
  const client = await serverSupabaseClient<Database>(event);
  const projectId = event.context.params?.projectId;
  const config = useRuntimeConfig();

  if (!user || !projectId) {
    throw createError({ statusCode: 401, statusMessage: "Unauthorized" });
  }

  // 1. Fetch Analytics Data Summary
  const userId = (user as any).id || (user as any).sub;

  // Verify ownership
  // @ts-ignore
  const { data: project } = await client
    .from("projects")
    .select("id, name, config")
    .eq("id", projectId)
    .eq("user_id", userId)
    .single();

  const projectData = project as any;

  if (!project) {
    throw createError({ statusCode: 403, statusMessage: "Forbidden" });
  }

  // Fetch Stats (Last 30 days)
  // @ts-ignore
  const { data: events } = await client
    .from("analytics_events")
    .select("event_type, metadata, created_at")
    .eq("project_id", projectId)
    .gte(
      "created_at",
      new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
    )
    .order("created_at", { ascending: true });

  const eventsList = (events || []) as any[];

  const stats = {
    total_views:
      eventsList.filter((e) => e.event_type === "page_view").length || 0,
    total_clicks:
      eventsList.filter((e) => e.event_type === "click").length || 0,
    top_pages: {} as Record<string, number>,
    top_actions: {} as Record<string, number>,
  };

  eventsList.forEach((e) => {
    if (e.event_type === "page_view") {
      const path = (e.metadata as any)?.path || "/";
      stats.top_pages[path] = (stats.top_pages[path] || 0) + 1;
    } else if (e.event_type === "click") {
      const action =
        (e.metadata as any)?.element_id ||
        (e.metadata as any)?.label ||
        "unknown";
      stats.top_actions[action] = (stats.top_actions[action] || 0) + 1;
    }
  });

  // 2. Call Gemini
  const genAI = new GoogleGenerativeAI(config.geminiApiKey);
  const model = genAI.getGenerativeModel({ model: "gemini-pro" });

  const prompt = `
    Analyze this website traffic data for the project "${projectData.name}":
    ${JSON.stringify(stats, null, 2)}

    Context:
    - This is a ${
      (projectData.config as any)?.site?.tagline || "landing page"
    } generated by AI.

    Your Task:
    1. Identify 1 key strength (what's working?).
    2. Identify 1 key weakness/drop-off point (e.g. high views but low clicks).
    3. Suggest 3 specific, actionable improvements to increase conversion.

    Format the response in Markdown. Keep it professional but encouraging.
  `;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    return { insights: text };
  } catch (e) {
    console.error("Gemini Error:", e);
    throw createError({
      statusCode: 503,
      message: "AI Service Unavailable",
    });
  }
});
