// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ai-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/ai-status.get').default>>>>
    }
    '/api/download-kit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/download-kit.post').default>>>>
    }
    '/api/generate-page': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/generate-page.post').default>>>>
    }
    '/api/rewrite': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/rewrite.post').default>>>>
    }
    '/api/wp-posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/wp-posts.get').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/index').default>>>>
    }
  }
}
export {}