export function generateAnalyticsApi() {
  return `import { serverSupabaseClient } from "#supabase/server";

export default defineEventHandler(async (event) => {
  const body = await readBody(event);
  const { projectId, eventType, metadata } = body;

  if (!projectId || !eventType) {
    throw createError({
      statusCode: 400,
      statusMessage: "Missing projectId or eventType",
    });
  }

  // --- ADAPTER: Supabase (Default) ---
  // To use MySQL/Postgres/MongoDB, replace this block with your DB call.
  // See ANALYTICS.md for details.
  const client = await serverSupabaseClient(event);

  const { error } = await client.from("analytics_events").insert({
    project_id: projectId,
    event_type: eventType,
    metadata: metadata || {},
  });

  if (error) {
    console.error("Analytics Error:", error);
    return { success: false };
  }
  // --- END ADAPTER ---

  return { success: true };
});
`;
}

export function generateAnalyticsManual() {
  return `# 📊 Minions Analytics Kit - User Manual

Welcome to the **Minions Analytics Kit**, a privacy-first, self-hosted analytics solution included with your generated project.

---

## 🚀 Quick Start (Supabase Recommended)

### 1. Database Setup
1.  Go to [Supabase.com](https://supabase.com) and create a new project.
2.  Go to the **SQL Editor** in your Supabase dashboard.
3.  Open the file \`database/analytics_schema.sql\` from this project.
4.  Copy, paste, and run the SQL to create the \`analytics_events\` table.

### 2. Connect Your Project
Add variables to \`.env\`:

\`\`\`bash
SUPABASE_URL="https://your-project-id.supabase.co"
SUPABASE_KEY="your-anon-key"
\`\`\`

---

## 🛠️ Customizing (MySQL, MongoDB, etc.)

We designed the Analytics API to be **Database Agnostic**.

### How to switch?

Open \`server/api/analytics/track.post.ts\`. You will see a section labeled \`// ADAPTER: Supabase\`.
Replace that block with your ORM call (Prisma, Drizzle, etc.).

\`\`\`typescript
// Example: Prisma
await prisma.analyticsEvent.create({
  data: { projectId, eventType, metadata }
})
\`\`\`

Happy Tracking! 📈
`;
}

export function generateAnalyticsComposable() {
  return `export const useAnalytics = () => {
  const config = useRuntimeConfig();

  // Helper to send data to our API
  const sendEvent = async (projectId: number | string, eventType: string, metadata: any = {}) => {
    try {
      await $fetch("/api/analytics/track", {
        method: "POST",
        body: {
          projectId,
          eventType,
          metadata,
        },
      });
    } catch (e) {
      // Silently fail for analytics to not disrupt UX
      console.warn("[Analytics] Failed to track:", e);
    }
  };

  const trackPageView = (projectId: number | undefined, path: string) => {
    if (!projectId) return;
    sendEvent(projectId, "page_view", { path });
  };

  const trackClick = (projectId: number | undefined, elementId: string, label?: string) => {
    if (!projectId) return;
    sendEvent(projectId, "click", { element_id: elementId, label });
  };

  return {
    trackPageView,
    trackClick,
  };
};
`;
}

export function generateAnalyticsMigration() {
  return `-- Run this in your Supabase SQL Editor to enable Analytics

CREATE TABLE IF NOT EXISTS analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL, -- 'page_view', 'click'
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_analytics_project_time ON analytics_events(project_id, created_at);
ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

-- Allow public inserts (so visitors can log events)
CREATE POLICY "Public can insert events" ON analytics_events FOR INSERT WITH CHECK (true);

-- Allow owners to view
CREATE POLICY "Owners can view analytics" ON analytics_events FOR SELECT USING (auth.uid() = (select user_id from projects where id = analytics_events.project_id));
`;
}
