import type { PageConfig } from "@minions/shared";

export function generateReadme(
  stack: string,
  config: PageConfig,
  isProject = false
) {
  const base = `# ${config.site?.siteName || "Generated Project"}

Generated by MINIONS AI Builder.

\`\`\`bash
# Install dependencies
npm install

# Run development server
npm run dev
\`\`\`

## 🛠 Identity & Customization

- **Project Name**: You can rename the project folder to match your site.
- **Identity**: Update the \`name\` field in \`package.json\` to your preferred identifier.
- **Content**: All content is managed in \`data/${
    isProject ? "project-config.json" : "page-config.json"
  }\`.
- **Primary Color**: Change \`site.primaryColor\` in the config file to update the theme.
`;

  if (stack === "vue-vite") {
    return `${base}
## Stack: Vue 3 + Vite

This project uses **Vite** for lightning fast development.

### Folder Structure
- \`src/App.vue\`: The root component.
- \`src/main.ts\`: Entry point, mounts Vue.
- \`src/router.ts\`: Vue Router configuration.
- \`src/components/sections/\`: All UI sections (Hero, Features, etc.).
- \`src/pages/\`: Page wrappers using \`PageRenderer\`.
- \`src/data/project-config.json\`: The single source of truth for content.

### Integration Guide

**1. Using Components:**
All sections are pure Vue components. You can import them anywhere:
\`\`\`vue
<script setup>
import HeroSection from './components/sections/HeroSection.vue'
</script>

<template>
  <HeroSection :config="{...}" />
</template>
\`\`\`

**2. Routing:**
We use \`vue-router\`. Routes are generated automatically in \`src/router.ts\` based on your pages. Add new pages by creating a Vue file and adding a route there.

**3. Theming:**
TailwindCSS is configured in \`tailwind.config.js\`.
- Change primary colors in \`src/data/project-config.json\` (site.primaryColor).
- Dark mode is class-based. Toggle it via the \`dark\` class on the HTML element.

### Deployment
Build using \`npm run build\`. The output will be in \`dist/\`. You can deploy this static folder anywhere (Vercel, Netlify, S3).
`;
  }

  if (stack === "wordpress-theme") {
    return `${base}
## WordPress Headless Configuration

This project is configured as a Headless Frontend for your WordPress site.

**WordPress URL**: \`${config.backend?.wordpress?.baseUrl || "NOT_SET"}\`

### How it works
1. The **PageRenderer** reads from \`data/${
      isProject ? "project-config.json" : "page-config.json"
    }\`.
2. The **BlogListSection** fetches posts from your WordPress API.
3. You can edit content in WordPress (Posts) or in the JSON (Layouts).

### Deployment
Deploy this folder to Vercel/Netlify. It acts as the "View" layer for your WP data.
`;
  }

  if (stack === "nuxt") {
    let structureDocs = `
- **Engine**: Nuxt 3
- **Styling**: TailwindCSS
- **Components**: \`components/sections/*\`
- **Configuration**: \`data/${
      isProject ? "project-config.json" : "page-config.json"
    }\`
`;

    if (isProject) {
      structureDocs += `
- **Pages**: 
  - \`pages/index.vue\` (Home)
  - Other pages generated based on project structure.
  - Each page file reads its config from the central JSON.
`;
    }

    return `${base}
## Architecture

${structureDocs}

Open \`app.vue\` and \`pages/\` to see how the \`PageRenderer\` is used.
`;
  }

  return `# Project Export
  
stack: ${stack}

See docs for manual integration.
`;
}

export function generateDeployMd() {
  return `# Deployment Guide

## Vercel (Recommended)

1. **Install Vercel CLI** (Optional but faster):
   \`\`\`bash
   npm i -g vercel
   vercel
   \`\`\`

2. **Drag & Drop**:
   - Go to [Vercel Dashboard](https://vercel.com/dashboard).
   - Drag this project folder into the "Import Project" area.
   - Framework Preset: **Nuxt.js** (or Vite if using Vue stack).
   - Build Command: \`npm run build\` (default).
   - Output Directory: \`.output\` (Nuxt) or \`dist\` (Vite).

## Netlify

1. Drag and drop the folder.
2. Build Command: \`npm run build\`.
3. Publish Directory: \`dist\`.

## Docker

\`\`\`dockerfile
FROM node:18-alpine
WORKDIR /app
COPY . .
RUN npm install && npm run build
CMD ["node", ".output/server/index.mjs"]
\`\`\`
`;
}
