import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const inputPath = path.join(rootDir, "landing-example.json");
const outputDir = path.join(rootDir, "data");
const outputPath = path.join(outputDir, "landing-data");

function main() {
  const raw = fs.readFileSync(inputPath, "utf-8");

  JSON.parse(raw);

  const fileContent = `// This file is auto-generated from landing-example.json
// Do not edit this file directly. Instead, edit landing-example.json and run the generator script.

import type { PageConfig } from '@minions/shared';

export const pageConfig: PageConfig = ${raw};
`;

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(outputPath, fileContent, "utf-8");

  console.log("Generated data/landing-data from landing-example.json");
}

main();
